name: Actualizar eventos.json

on:
  schedule:
    - cron: "*/5 * * * *"  # Cada 5 minutos
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Ejecutar scraper
        run: |
          pip install requests
          python scraper.py

      - name: Hacer commit de eventos.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add eventos.json
          git commit -m "Actualización automática de eventos" || echo "Sin cambios"
          git push
